name: release version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v1

      - name: Build and Test
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "clean install"

      - name: Release
        uses: qcastel/github-actions-maven-release@master
        with:
          release-branch-name: "main"

          git-release-bot-name: "bot-idhub"
          git-release-bot-email: "bot@idhub.io"

          access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}

          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip -Dmaven.deploy.skip=true"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}